// ignore: depend_on_referenced_packages
import 'package:freezed_annotation/freezed_annotation.dart';
part 'inventory.freezed.dart';
part 'inventory.g.dart';

@freezed
class Inventory with _$Inventory {
  const factory Inventory({
    @Default("") String id,
    @Default("") String brand,
    @Default("") String model,
    @Default("") String owner,
    @Default("") String price,
    @Default("") String color,
    @Default("") String registrationYear,
    @Default("") String passingCode,
    @Default("") String kmsDriven,
    @Default("") String engineCapacity,
    @Default("") String variant,
    @Default("") String fueltype,
    @Default("") String transmission,
    @Default("") String insurance,
    @Default("") String ownership,
    @Default("") String status,
    @Default("") String airbags,
    @Default(false) bool isofix,
    @Default(false) bool abs,
    @Default(false) bool centralLocking,
    @Default(false) bool ebd,
    @Default(false) bool tpms,
    @Default(false) bool hillHoldControl,
    @Default(false) bool hillDecentControl,
    @Default(false) bool tractionControl,
    @Default(false) bool rearDefogger,
    @Default(false) bool frontFogLights,
    @Default("") String instrumentPanelType,
    @Default(false) bool bluetoothCompatibility,
    @Default(false) bool steeringMountedControls,
    @Default(false) bool audioSystem,
    @Default(false) bool airConditioner,
    @Default(false) bool powerWindowsFront,
    @Default("") String steeringWheelMaterial,
    @Default("") String parkingAssistRear,
    @Default(false) bool powerOutlet12V,
    @Default(false) bool steeringAdjustment,
    @Default(false) bool seatUpholstery,
    @Default(false) bool pushButtonStart,
    @Default(false) bool cruiseControl,
    @Default(false) bool ventillatedSeatsFront,
    @Default(false) bool rearAC,
    @Default("") String displacement,
    @Default("") String cylinders,
    @Default("") String gearBoxNumberOfGears,
    @Default("") String noOfDiskBreaks,
    @Default("") String groundClearance,
    @Default("") String seatingCapacity,
    @Default("") String bootspace,
    @Default("") String widthInMM,
    @Default("") String lengthInMM,
    @Default("") String wheelBaseInMM,
    @Default("") String fuelTankCapacity,
    @Default("") String maxPowerInBHP,
    @Default("") String maxPowerInRPM,
    @Default("") String emissionStandard,
    @Default("") String maxTorqueInNM,
    @Default("") String headlampLensType,
    @Default("") String headlampBulbTypeHighBeam,
    @Default("") String headlampBulbTypeLowBeam,
    @Default("") String rimTypeFront,
    @Default("") String rimTypeRear,
    @Default(false) bool dayrimeRunningLights,
    @Default(false) bool electricallyFoldableMirros,
  }) = _Inventory;

  factory Inventory.fromJson(Map<String, Object?> json) =>
      _$InventoryFromJson(json);
}
