// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'inventory.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$InventoryImpl _$$InventoryImplFromJson(Map<String, dynamic> json) =>
    _$InventoryImpl(
      id: json['id'] as String? ?? "",
      brand: json['brand'] as String? ?? "",
      model: json['model'] as String? ?? "",
      owner: json['owner'] as String? ?? "",
      price: json['price'] as String? ?? "",
      color: json['color'] as String? ?? "",
      registrationYear: json['registrationYear'] as String? ?? "",
      passingCode: json['passingCode'] as String? ?? "",
      kmsDriven: json['kmsDriven'] as String? ?? "",
      engineCapacity: json['engineCapacity'] as String? ?? "",
      variant: json['variant'] as String? ?? "",
      fueltype: json['fueltype'] as String? ?? "",
      transmission: json['transmission'] as String? ?? "",
      insurance: json['insurance'] as String? ?? "",
      ownership: json['ownership'] as String? ?? "",
      status: json['status'] as String? ?? "",
      airbags: json['airbags'] as String? ?? "",
      isofix: json['isofix'] as bool? ?? false,
      abs: json['abs'] as bool? ?? false,
      centralLocking: json['centralLocking'] as bool? ?? false,
      ebd: json['ebd'] as bool? ?? false,
      tpms: json['tpms'] as bool? ?? false,
      hillHoldControl: json['hillHoldControl'] as bool? ?? false,
      hillDecentControl: json['hillDecentControl'] as bool? ?? false,
      tractionControl: json['tractionControl'] as bool? ?? false,
      rearDefogger: json['rearDefogger'] as bool? ?? false,
      frontFogLights: json['frontFogLights'] as bool? ?? false,
      instrumentPanelType: json['instrumentPanelType'] as String? ?? "",
      bluetoothCompatibility: json['bluetoothCompatibility'] as bool? ?? false,
      steeringMountedControls:
          json['steeringMountedControls'] as bool? ?? false,
      audioSystem: json['audioSystem'] as bool? ?? false,
      airConditioner: json['airConditioner'] as bool? ?? false,
      powerWindowsFront: json['powerWindowsFront'] as bool? ?? false,
      steeringWheelMaterial: json['steeringWheelMaterial'] as String? ?? "",
      parkingAssistRear: json['parkingAssistRear'] as String? ?? "",
      powerOutlet12V: json['powerOutlet12V'] as bool? ?? false,
      steeringAdjustment: json['steeringAdjustment'] as bool? ?? false,
      seatUpholstery: json['seatUpholstery'] as bool? ?? false,
      pushButtonStart: json['pushButtonStart'] as bool? ?? false,
      cruiseControl: json['cruiseControl'] as bool? ?? false,
      ventillatedSeatsFront: json['ventillatedSeatsFront'] as bool? ?? false,
      rearAC: json['rearAC'] as bool? ?? false,
      displacement: json['displacement'] as String? ?? "",
      cylinders: json['cylinders'] as String? ?? "",
      gearBoxNumberOfGears: json['gearBoxNumberOfGears'] as String? ?? "",
      noOfDiskBreaks: json['noOfDiskBreaks'] as String? ?? "",
      groundClearance: json['groundClearance'] as String? ?? "",
      seatingCapacity: json['seatingCapacity'] as String? ?? "",
      bootspace: json['bootspace'] as String? ?? "",
      widthInMM: json['widthInMM'] as String? ?? "",
      lengthInMM: json['lengthInMM'] as String? ?? "",
      wheelBaseInMM: json['wheelBaseInMM'] as String? ?? "",
      fuelTankCapacity: json['fuelTankCapacity'] as String? ?? "",
      maxPowerInBHP: json['maxPowerInBHP'] as String? ?? "",
      maxPowerInRPM: json['maxPowerInRPM'] as String? ?? "",
      emissionStandard: json['emissionStandard'] as String? ?? "",
      maxTorqueInNM: json['maxTorqueInNM'] as String? ?? "",
      headlampLensType: json['headlampLensType'] as String? ?? "",
      headlampBulbTypeHighBeam:
          json['headlampBulbTypeHighBeam'] as String? ?? "",
      headlampBulbTypeLowBeam: json['headlampBulbTypeLowBeam'] as String? ?? "",
      rimTypeFront: json['rimTypeFront'] as String? ?? "",
      rimTypeRear: json['rimTypeRear'] as String? ?? "",
      dayrimeRunningLights: json['dayrimeRunningLights'] as bool? ?? false,
      electricallyFoldableMirros:
          json['electricallyFoldableMirros'] as bool? ?? false,
    );

Map<String, dynamic> _$$InventoryImplToJson(_$InventoryImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'brand': instance.brand,
      'model': instance.model,
      'owner': instance.owner,
      'price': instance.price,
      'color': instance.color,
      'registrationYear': instance.registrationYear,
      'passingCode': instance.passingCode,
      'kmsDriven': instance.kmsDriven,
      'engineCapacity': instance.engineCapacity,
      'variant': instance.variant,
      'fueltype': instance.fueltype,
      'transmission': instance.transmission,
      'insurance': instance.insurance,
      'ownership': instance.ownership,
      'status': instance.status,
      'airbags': instance.airbags,
      'isofix': instance.isofix,
      'abs': instance.abs,
      'centralLocking': instance.centralLocking,
      'ebd': instance.ebd,
      'tpms': instance.tpms,
      'hillHoldControl': instance.hillHoldControl,
      'hillDecentControl': instance.hillDecentControl,
      'tractionControl': instance.tractionControl,
      'rearDefogger': instance.rearDefogger,
      'frontFogLights': instance.frontFogLights,
      'instrumentPanelType': instance.instrumentPanelType,
      'bluetoothCompatibility': instance.bluetoothCompatibility,
      'steeringMountedControls': instance.steeringMountedControls,
      'audioSystem': instance.audioSystem,
      'airConditioner': instance.airConditioner,
      'powerWindowsFront': instance.powerWindowsFront,
      'steeringWheelMaterial': instance.steeringWheelMaterial,
      'parkingAssistRear': instance.parkingAssistRear,
      'powerOutlet12V': instance.powerOutlet12V,
      'steeringAdjustment': instance.steeringAdjustment,
      'seatUpholstery': instance.seatUpholstery,
      'pushButtonStart': instance.pushButtonStart,
      'cruiseControl': instance.cruiseControl,
      'ventillatedSeatsFront': instance.ventillatedSeatsFront,
      'rearAC': instance.rearAC,
      'displacement': instance.displacement,
      'cylinders': instance.cylinders,
      'gearBoxNumberOfGears': instance.gearBoxNumberOfGears,
      'noOfDiskBreaks': instance.noOfDiskBreaks,
      'groundClearance': instance.groundClearance,
      'seatingCapacity': instance.seatingCapacity,
      'bootspace': instance.bootspace,
      'widthInMM': instance.widthInMM,
      'lengthInMM': instance.lengthInMM,
      'wheelBaseInMM': instance.wheelBaseInMM,
      'fuelTankCapacity': instance.fuelTankCapacity,
      'maxPowerInBHP': instance.maxPowerInBHP,
      'maxPowerInRPM': instance.maxPowerInRPM,
      'emissionStandard': instance.emissionStandard,
      'maxTorqueInNM': instance.maxTorqueInNM,
      'headlampLensType': instance.headlampLensType,
      'headlampBulbTypeHighBeam': instance.headlampBulbTypeHighBeam,
      'headlampBulbTypeLowBeam': instance.headlampBulbTypeLowBeam,
      'rimTypeFront': instance.rimTypeFront,
      'rimTypeRear': instance.rimTypeRear,
      'dayrimeRunningLights': instance.dayrimeRunningLights,
      'electricallyFoldableMirros': instance.electricallyFoldableMirros,
    };
